### ISSUE TITLE
Git tags for versioning

### ISSUE THREAD

**Issue by beeceej** [dirt-simple/terraform-aws-fargate-cpu-memory-values#3]
What if there's a breaking change we want to merge in but not break existing consumers of this module? might be worth tagging releases so people can choose an upgrade path on their own time.

**Comment by cdornsife** [comment]
Yeah, tagging would work. I usually prefer branches but in this case a tag might make good sense.

**Comment by cdornsife** [comment]
The tag v0.12.28 was created.
